// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	listRoots: () => typedError<GameRoot[], string>(__TAURI_INVOKE("list_roots")),
	listInstances: (root: string) => typedError<InstanceSummary[], string>(__TAURI_INVOKE("list_instances", { root })),
	/**  取实例的游戏目录绝对路径(供「打开游戏目录」用前端 shell.open 打开)。 */
	instanceDir: (root: string, id: string) => typedError<string, string>(__TAURI_INVOKE("instance_dir", { root, id })),
	/**
	 *  取实例某个子目录的绝对路径并确保其存在(供「打开目录」用前端 shell.open 打开)。
	 *  sub = "mods" / "resourcepacks" / "shaderpacks" / "datapacks" / "saves" / "screenshots" / "config"。
	 */
	instanceSubdir: (root: string, id: string, sub: string) => typedError<string, string>(__TAURI_INVOKE("instance_subdir", { root, id, sub })),
	/**  用系统文件管理器打开一个路径(目录/文件)。直接调 OS,绕开 shell 插件只放行 URL 的作用域。 */
	revealPath: (path: string) => typedError<null, string>(__TAURI_INVOKE("reveal_path", { path })),
	/**
	 *  删除一个实例。复用 mc-core 的 lifecycle::delete_instance:优先移入系统回收站
	 *  (可恢复),无 GUI 时回退永久删除;目录不存在视为已删除(幂等)。前端须先确认。
	 */
	deleteInstance: (root: string, id: string) => typedError<null, string>(__TAURI_INVOKE("delete_instance", { root, id })),
	/**
	 *  复制一个实例:整目录复制 src_id → 新实例(id 由 new_name 唯一化),并把新实例
	 *  的 instance.json name 设为 new_name。返回新实例 id。
	 */
	copyInstance: (root: string, srcId: string, newName: string) => typedError<string, string>(__TAURI_INVOKE("copy_instance", { root, srcId, newName })),
	/**
	 *  从零创建实例:装核心(原版或 + loader)→ 写命名实例。进度走 install://progress。
	 *  loader = "vanilla" / "fabric" / "quilt" / "forge" / "neoforge";forge/neoforge 需 loader_version。
	 */
	createInstance: (root: string, name: string, mcVersion: string, loader: string, loaderVersion: string | null) => typedError<string, string>(__TAURI_INVOKE("create_instance", { root, name, mcVersion, loader, loaderVersion })),
	/**
	 *  给一个已存在的实例添加 / 切换 mod 加载器(core)。进度走 install://progress。
	 *  loader = "fabric" / "quilt" / "forge" / "neoforge"(拒绝 vanilla / 无效值);
	 *  forge/neoforge 需 loader_version。返回之后应使用的实例 id —— 多数情况与传入 id
	 *  相同,但「实例目录本身就是裸原版」的退化情形会返回一个新 id(避免自环)。
	 */
	installLoader: (root: string, id: string, mcVersion: string, loader: string, loaderVersion: string | null) => typedError<string, string>(__TAURI_INVOKE("install_loader", { root, id, mcVersion, loader, loaderVersion })),
	/**
	 *  列出某 loader 在指定 MC 版本下的可用构建号(新建实例的版本选择器用)。
	 *  loader = "forge" / "neoforge" / "fabric" / "quilt";其它(vanilla 等)返回空。
	 *  返回值按「新→旧」排序,前端默认选第一个。网络/解析失败时由前端回退到手填输入框。
	 */
	listLoaderVersions: (loader: string, mcVersion: string) => typedError<string[], string>(__TAURI_INVOKE("list_loader_versions", { loader, mcVersion })),
	/**  读取某实例的配置(名字/内存/Java/JVM 参数/窗口…)。文件缺失返回默认值。 */
	getInstanceConfig: (root: string, id: string) => typedError<InstanceConfig_Serialize, string>(__TAURI_INVOKE("get_instance_config", { root, id })),
	/**  写某实例的配置(原子写入 instance.json)。 */
	setInstanceConfig: (root: string, id: string, config: InstanceConfig_Deserialize) => typedError<null, string>(__TAURI_INVOKE("set_instance_config", { root, id, config })),
	/**  读取本机物理内存总量(MiB)。纯探测,不读实例。 */
	systemMemory: () => typedError<SystemMemory, string>(__TAURI_INVOKE("system_memory")),
	/**
	 *  为某实例推荐一个最大堆内存(MiB):综合本机物理内存与该实例已装 mod 数量。
	 *  纯启发式(见 [`mc_core::system::suggest_memory_mb`]),按需读取一次 mod 列表 + 系统内存。
	 */
	suggestInstanceMemory: (root: string, id: string) => typedError<number, string>(__TAURI_INVOKE("suggest_instance_memory", { root, id })),
	/**
	 *  设置某实例的标签:加载配置 → 规范化(去空白、去空项、去重、保序)→ 写回。
	 *  自由格式标签,供库页分组 / 按标签筛选用。
	 */
	setInstanceTags: (root: string, id: string, tags: string[]) => typedError<null, string>(__TAURI_INVOKE("set_instance_tags", { root, id, tags })),
	/**
	 *  把任意图片设为实例图标(拷贝到 `versions/<id>/icon.png`)。source 为本地文件绝对路径。
	 *  之后 list_instances 会把它探测为 data URL 回传前端。
	 */
	setInstanceIcon: (root: string, id: string, source: string) => typedError<null, string>(__TAURI_INVOKE("set_instance_icon", { root, id, source })),
	/**
	 *  给整合包来源的实例补齐图标:实例还没有本地 `icon.png` 时,下载 `icon_url` 写入。
	 *  早于「安装即存图标」特性安装的实例本地没图标,详情页发现缺失时调用一次,让侧栏/首页/详情
	 *  统一显示整合包真实 logo,而不再退回默认像素占位。返回 `true` 表示这次补上了。
	 *  已有图标或下载失败都安静返回 `false`(图标纯展示性,失败不打断任何流程)。
	 */
	backfillInstanceIcon: (root: string, id: string, iconUrl: string) => typedError<boolean, string>(__TAURI_INVOKE("backfill_instance_icon", { root, id, iconUrl })),
	/**  列出某实例 mods 目录里的 mod(含启停态)。 */
	instanceMods: (root: string, id: string) => typedError<ModInfo[], string>(__TAURI_INVOKE("instance_mods", { root, id })),
	/**  启用/停用一个 mod(改 `.jar` ↔ `.jar.disabled`)。file_name 为 list 返回的稳定标识。 */
	setModEnabled: (root: string, id: string, fileName: string, enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_mod_enabled", { root, id, fileName, enabled })),
	/**  删除一个 mod 文件。 */
	deleteMod: (root: string, id: string, fileName: string) => typedError<null, string>(__TAURI_INVOKE("delete_mod", { root, id, fileName })),
	/**
	 *  把一个 mod 的最新兼容版本装进实例。`provider` 缺省 `modrinth`:
	 *  - Modrinth 走核心的「装最新版 + 解析 required 依赖」路径。
	 *  - CurseForge 经 provider 取最新兼容版本直接落盘(CF 文件级不带依赖,故不解析);
	 *    遇作者禁分发的文件经 `blocked` 回传,前端走手动下载流而非假装成功。
	 */
	installMod: (root: string, id: string, project: string, mcVersion: string, loader: string, provider: string | null) => typedError<ModInstallReport, string>(__TAURI_INVOKE("install_mod", { root, id, project, mcVersion, loader, provider })),
	/**
	 *  安装一个**指定版本**(by version id)到实例对应位置。`provider` 缺省 `modrinth`,
	 *  `project` 是该版本所属项目 id(CurseForge 经 `get_files_bulk` 反查需要,Modrinth 可空)。
	 *  target = "mod" / "resourcepack" / "shader" / "datapack"。
	 * 
	 *  mod(仅 Modrinth):在装入所选版本的同时解析它声明的 required 依赖(取各依赖最新兼容版本),
	 *  与「装最新版」一致 —— 避免选版安装出一个缺前置、进不去游戏的孤立 jar。需要 `mc_version` +
	 *  `loader` 才能给依赖挑兼容版本;缺省时退回只装主文件。packs 与 CurseForge 不涉及依赖。
	 *  CurseForge 作者禁分发的文件经 `blocked` 回传,前端走手动下载流而非假装成功。
	 */
	installVersionFile: (root: string, id: string, target: string, versionId: string, mcVersion: string | null, loader: string | null, world: string | null, provider: string | null, project: string | null) => typedError<VersionInstallReport, string>(__TAURI_INVOKE("install_version_file", { root, id, target, versionId, mcVersion, loader, world, provider, project })),
	/**  检查实例里已启用 mod 的更新(对每个 jar 的 sha1 问 Modrinth 当前 loader/版本下的最新版)。 */
	checkModUpdates: (root: string, id: string, mcVersion: string, loader: string) => typedError<ModUpdate[], string>(__TAURI_INVOKE("check_mod_updates", { root, id, mcVersion, loader })),
	/**  应用一个 mod 更新:下载新版本进 mods/ 并删掉旧文件。update 为 check_mod_updates 返回的条目。 */
	applyModUpdate: (root: string, id: string, update: ModUpdate) => typedError<null, string>(__TAURI_INVOKE("apply_mod_update", { root, id, update })),
	/**
	 *  把一个本地文件拖拽导入实例:按 target 拷贝到对应子目录,返回落盘文件名。
	 *  target = "mod" / "resourcepack" / "shader" / "datapack"。
	 */
	importLocalResource: (root: string, id: string, target: string, path: string, world: string | null) => typedError<string, string>(__TAURI_INVOKE("import_local_resource", { root, id, target, path, world })),
	/**  列出某实例下指定类型的包(资源包 / 光影 / 数据包),含启停态。 */
	instancePacks: (root: string, id: string, kind: PackKind, world: string | null) => typedError<PackInfo_Serialize[], string>(__TAURI_INVOKE("instance_packs", { root, id, kind, world })),
	/**  启用/停用一个包(改 `.zip` ↔ `.zip.disabled`)。 */
	setPackEnabled: (root: string, id: string, kind: PackKind, fileName: string, enabled: boolean, world: string | null) => typedError<null, string>(__TAURI_INVOKE("set_pack_enabled", { root, id, kind, fileName, enabled, world })),
	/**  删除一个包(移入系统回收站,可找回)。 */
	deletePack: (root: string, id: string, kind: PackKind, fileName: string, world: string | null) => typedError<null, string>(__TAURI_INVOKE("delete_pack", { root, id, kind, fileName, world })),
	/**
	 *  安装一个包(资源包 / 光影 / 数据包)的最新兼容版本到实例对应目录。`provider` 缺省
	 *  `modrinth`。返回落盘文件名;CurseForge 作者禁分发的文件经 `blocked` 回传(file 为空),
	 *  前端走手动下载流而非假装成功。
	 */
	installPack: (root: string, id: string, kind: PackKind, project: string, mcVersion: string, world: string | null, provider: string | null) => typedError<VersionInstallReport, string>(__TAURI_INVOKE("install_pack", { root, id, kind, project, mcVersion, world, provider })),
	/**  列出某实例的截图(仅元数据,按修改时间倒序)。 */
	instanceScreenshots: (root: string, id: string) => typedError<ScreenshotInfo[], string>(__TAURI_INVOKE("instance_screenshots", { root, id })),
	/**  按需读取一张截图为 data URL(UI 滚动到哪张才取哪张)。 */
	readScreenshot: (root: string, id: string, fileName: string) => typedError<string, string>(__TAURI_INVOKE("read_screenshot", { root, id, fileName })),
	/**  删除一张截图(移入系统回收站,可找回)。 */
	deleteScreenshot: (root: string, id: string, fileName: string) => typedError<null, string>(__TAURI_INVOKE("delete_screenshot", { root, id, fileName })),
	/**  列出某实例的存档世界(名字/模式/大小/上次游玩…)。 */
	instanceWorlds: (root: string, id: string) => typedError<WorldInfo[], string>(__TAURI_INVOKE("instance_worlds", { root, id })),
	/**  列出某实例已保存的多人服务器(读 game_dir/servers.dat;文件不存在 → 空表)。 */
	instanceServers: (root: string, id: string) => typedError<SavedServer[], string>(__TAURI_INVOKE("instance_servers", { root, id })),
	/**  向某实例的 servers.dat 追加一条多人服务器(name 可空,address 必填)。 */
	addInstanceServer: (root: string, id: string, name: string, address: string) => typedError<null, string>(__TAURI_INVOKE("add_instance_server", { root, id, name, address })),
	/**  Ping 一个 Minecraft 服务器,返回在线/人数/延迟/MOTD(失败时返回离线状态,从不报错)。 */
	pingServer: (address: string) => typedError<ServerStatus, string>(__TAURI_INVOKE("ping_server", { address })),
	/**  删除一个存档世界(移入系统回收站,可找回)。 */
	deleteWorld: (root: string, id: string, folder: string) => typedError<null, string>(__TAURI_INVOKE("delete_world", { root, id, folder })),
	/**
	 *  把一个存档打成 zip 备份到 dest_path(完整 .zip 文件路径,由 UI 的另存为对话框给出),
	 *  返回写出的 zip 绝对路径。
	 */
	backupWorld: (root: string, id: string, folder: string, destPath: string) => typedError<string, string>(__TAURI_INVOKE("backup_world", { root, id, folder, destPath })),
	/**  重命名存档的显示名(改 level.dat 的 LevelName,不改文件夹名)。 */
	renameWorld: (root: string, id: string, folder: string, newName: string) => typedError<null, string>(__TAURI_INVOKE("rename_world", { root, id, folder, newName })),
	/**  从一个 .zip 导入世界到实例 saves/,返回新世界文件夹名。zip 内需含 level.dat。 */
	importWorldZip: (root: string, id: string, path: string) => typedError<string, string>(__TAURI_INVOKE("import_world_zip", { root, id, path })),
	listVersions: (snapshot: boolean) => typedError<ManifestVersion[], string>(__TAURI_INVOKE("list_versions", { snapshot })),
	listAccounts: () => typedError<AccountSummary[], string>(__TAURI_INVOKE("list_accounts")),
	/**
	 *  Step ① of Microsoft login: start the device-code flow. The UI shows
	 *  `user_code` and opens `verification_uri`, then calls [`msa_login_poll`].
	 */
	msaLoginStart: () => typedError<DeviceCodeDto, string>(__TAURI_INVOKE("msa_login_start")),
	/**
	 *  Step ② of Microsoft login: block until the user finishes in the browser,
	 *  run the full Xbox → XSTS → Minecraft → profile chain, then persist and
	 *  select the resulting account.
	 */
	msaLoginPoll: (deviceCode: string, interval: number) => typedError<AccountSummary, string>(__TAURI_INVOKE("msa_login_poll", { deviceCode, interval })),
	/**  Add (or update) an offline account from a username and select it. */
	addOfflineAccount: (name: string) => typedError<AccountSummary, string>(__TAURI_INVOKE("add_offline_account", { name })),
	/**
	 *  外置登录(Yggdrasil / authlib-injector):用 base + 用户名 + 密码登录第三方皮肤站,
	 *  落库为 Yggdrasil 账号并选中。启动时会自动注入 authlib-injector。
	 */
	yggdrasilLogin: (base: string, username: string, password: string) => typedError<AccountSummary, string>(__TAURI_INVOKE("yggdrasil_login", { base, username, password })),
	/**  Switch the active account. */
	selectAccount: (uuid: string) => typedError<null, string>(__TAURI_INVOKE("select_account", { uuid })),
	/**  Remove an account by uuid. */
	removeAccount: (uuid: string) => typedError<null, string>(__TAURI_INVOKE("remove_account", { uuid })),
	/**
	 *  显式刷新当前选中的微软账号的登录(免浏览器,用 refresh_token)。返回是否执行了续期。
	 *  失败(refresh_token 失效)时返回错误,UI 据此提示重新登录。
	 */
	refreshAccount: () => typedError<boolean, string>(__TAURI_INVOKE("refresh_account")),
	/**  读取某微软账号的皮肤 / 披风资料。 */
	skinProfile: (accountUuid: string) => typedError<ProfileSkins, string>(__TAURI_INVOKE("skin_profile", { accountUuid })),
	/**  上传本地 PNG 作为新皮肤。`variant` 为 `classic` / `slim`。返回更新后的资料。 */
	skinUpload: (accountUuid: string, path: string, variant: string) => typedError<ProfileSkins, string>(__TAURI_INVOKE("skin_upload", { accountUuid, path, variant })),
	/**  设置当前披风(`Some`)或隐藏披风(`None`)。返回更新后的资料。 */
	skinSetCape: (accountUuid: string, capeId: string | null) => typedError<ProfileSkins, string>(__TAURI_INVOKE("skin_set_cape", { accountUuid, capeId })),
	detectJava: () => typedError<JavaDto[], string>(__TAURI_INVOKE("detect_java")),
	/**
	 *  跨平台内容搜索:`provider` 缺省 `modrinth`(也可 `curseforge`,需配 CF key),`sort`
	 *  缺省按相关度。`facets` 是 Discover 的多选 facet 过滤(仅 Modrinth 消费)。经 Provider
	 *  注册表路由,统一返回 [`SearchHit`]。命令名保持 `modrinth_search` 以稳定绑定,但实际是
	 *  泛平台搜索。
	 */
	modrinthSearch: (query: string, kind: string, gameVersion: string | null, loader: string | null, limit: number | null, offset: number | null, provider: string | null, sort: string | null, facets: {
	/**  多选内容分类(每个各成一个 AND 组)。 */
	categories?: string[],
	/**  多选 loader(合成一个 OR 组)。 */
	loaders?: string[],
	/**  多选游戏版本(合成一个 OR 组)。 */
	game_versions?: string[],
	/**  运行环境:`"client"` / `"server"`(其余忽略)。 */
	environment?: string | null,
	/**  仅开源项目(License facet)。 */
	open_source?: boolean | null,
} | null) => typedError<SearchHit[], string>(__TAURI_INVOKE("modrinth_search", { query, kind, gameVersion, loader, limit, offset, provider, sort, facets })),
	/**
	 *  Modrinth 的 facet 分类法(内容分类 / loader / 游戏版本),供 Discover 渲染过滤面板。
	 *  进程内缓存(见 [`ModrinthApi::content_facets`]),仅 Modrinth 提供;CurseForge 不走此处。
	 */
	contentFacets: () => typedError<FacetTagsDto, string>(__TAURI_INVOKE("content_facets")),
	getTheme: () => typedError<ThemeConfig, string>(__TAURI_INVOKE("get_theme")),
	setTheme: (cfg: ThemeConfig) => typedError<null, string>(__TAURI_INVOKE("set_theme", { cfg })),
	installVersion: (root: string, id: string) => typedError<null, string>(__TAURI_INVOKE("install_version", { root, id })),
	/**
	 *  启动一个实例。进程被登记进 [`RunningGames`];生命周期通过事件回传 UI:
	 *  进度走 `launch://progress`,日志走 `game://log`,**真正 spawn 成功**后发
	 *  `game://started { id }`,进程退出后发 `game://exit { id, code, success, reason }`
	 *  (非零退出会跑崩溃诊断,把人话原因 + 建议一并带回)。
	 * 
	 *  同一实例已在运行时直接拒绝,避免重复开多个 JVM。
	 */
	launchInstance: (root: string, id: string, name: string, online: boolean, server: string | null) => typedError<null, string>(__TAURI_INVOKE("launch_instance", { root, id, name, online, server })),
	/**
	 *  停止一个正在运行的实例(向其 reaper 发停止信号;reaper 杀进程并广播 `game://exit`)。
	 *  实例不在运行时为 no-op。
	 */
	stopInstance: (id: string) => typedError<null, string>(__TAURI_INVOKE("stop_instance", { id })),
	/**  当前正在运行的实例 id 列表(供 UI 挂载时同步运行态)。 */
	runningInstances: () => typedError<string[], string>(__TAURI_INVOKE("running_instances")),
	/**
	 *  导入一个整合包(`.mrpack` / CurseForge zip / MultiMC / MCBBS,自动识别格式),
	 *  建好实例并返回其 id。`path` 可为归档文件,**或**未解压的 MultiMC/Prism 实例目录。
	 *  `blocked` 列出需用户手动下载的 CurseForge 文件。
	 */
	importModpack: (root: string, path: string, instanceId: string | null) => typedError<ImportOutcomeDto, string>(__TAURI_INVOKE("import_modpack", { root, path, instanceId })),
	/**
	 *  把实例导出为整合包。`target` ∈ `modrinth` | `curseforge` | `modlist`
	 *  (后者可 `modlist:md|json|csv|txt|html` 选子格式)。`dest` 非空时把产物移到该路径。
	 *  返回最终文件路径。
	 */
	exportModpack: (root: string, instanceId: string, target: string, dest: string | null, packName: string, packVersion: string | null, mcVersion: string, loader: string | null, loaderVersion: string | null) => typedError<string, string>(__TAURI_INVOKE("export_modpack", { root, instanceId, target, dest, packName, packVersion, mcVersion, loader, loaderVersion })),
	/**
	 *  从 Modrinth 安装一个整合包:取该项目最新版本的 `.mrpack` 下载地址,经导入引擎
	 *  下载 + 识别 + 安装(原版 + loader + mods + overrides)成一个可启动实例。
	 */
	installModrinthModpack: (root: string, projectId: string, instanceId: string | null) => typedError<ImportOutcomeDto, string>(__TAURI_INVOKE("install_modrinth_modpack", { root, projectId, instanceId })),
	/**  从一个 `.mrpack` 直链安装整合包(详情页「安装此版本」用)。 */
	installModpackUrl: (root: string, url: string, instanceId: string | null) => typedError<ImportOutcomeDto, string>(__TAURI_INVOKE("install_modpack_url", { root, url, instanceId })),
	/**
	 *  浏览安装整合包(provider 感知,详情页「安装此版本」用):给定 `(provider, project, version_id)`,
	 *  经对应平台解析出整合包归档(Modrinth `.mrpack` / CurseForge `.zip`)的下载直链,再走与
	 *  [`install_modpack_url`] 完全相同的导入引擎(下载 → 识别格式 → 安装原版+loader+mods+overrides)。
	 * 
	 *  `provider` 缺省 `modrinth`。`name` 作为目标实例 id(`None` 时由整合包名派生唯一 id)。
	 *  安装的版本会写进实例 `instance.json` 的 source,供后续「检查更新」溯源。
	 * 
	 *  CurseForge 作者禁第三方分发时平台不给整合包直链(`file.url` 为空),此处把该包文件经
	 *  [`ImportOutcomeDto::blocked`] 的既有机制回传,让前端引导手动下载,而非抛不透明错误。
	 */
	installModpack: (root: string, provider: string | null, project: string, versionId: string, name: string | null, iconUrl: string | null) => typedError<ImportOutcomeDto, string>(__TAURI_INVOKE("install_modpack", { root, provider, project, versionId, name, iconUrl })),
	/**
	 *  列出一个项目的所有版本详情(详情页用:版本号/类型/MC/loader/发布时间/下载数/changelog
	 *  + 该版本下载地址)。`provider` 缺省 `modrinth`。CurseForge 经 provider 的统一版本模型
	 *  映射成同一 [`VersionDetail`] 形状(无 changelog/发布时间等富信息时留空),保持绑定稳定。
	 */
	modrinthVersions: (projectId: string, provider: string | null) => typedError<VersionDetail[], string>(__TAURI_INVOKE("modrinth_versions", { projectId, provider })),
	/**
	 *  取一个 Modrinth 项目的完整详情(简介标签页用:长描述正文 markdown + 画廊 +
	 *  关注数 + 源码/issue/wiki/discord 等外部链接)。
	 */
	modrinthProject: (projectId: string) => typedError<ProjectDetail, string>(__TAURI_INVOKE("modrinth_project", { projectId })),
	/**  读取全局设置(下载源/并发/默认内存/Java 路径/语言…)。缺失/损坏回退默认。 */
	getSettings: () => typedError<GlobalSettings, string>(__TAURI_INVOKE("get_settings")),
	/**  持久化全局设置(原子写 settings.json)。下载相关项下次构造下载器即生效。 */
	setSettings: (settings: GlobalSettings) => typedError<null, string>(__TAURI_INVOKE("set_settings", { settings })),
	/**
	 *  当前生效的「显示社交 UI」(kobeMC 账号 / 领域 / 好友)开关:用户显式设置优先,
	 *  否则按部署场景默认(便携·和实例同级 → 关;桌面独立版 → 开)。
	 */
	socialEnabled: () => typedError<boolean, string>(__TAURI_INVOKE("social_enabled")),
	/**  前端 webview 把启动/错误信息报到这里;经全局 tracing 落进统一日志(`[client]` 前缀)。 */
	logBoot: (msg: string) => __TAURI_INVOKE<void>("log_boot", { msg }),
	/**
	 *  前端统一日志入口:把 webview 的日志按级别转发到全局日志文件(`[client]` 前缀),
	 *  与本地数据层(`[daemon]`)的日志汇到同一处,方便对照排查。
	 *  level ∈ `error` / `warn` / `info` / `debug`(其它按 info 处理)。
	 */
	clientLog: (level: string, message: string) => __TAURI_INVOKE<void>("client_log", { level, message }),
	/**  返回全局日志目录(`<data_dir>/logs`,必要时创建),前端用 shell 打开它。 */
	openLogsDir: () => typedError<string, string>(__TAURI_INVOKE("open_logs_dir")),
	/**
	 *  读取最新日志文件的末尾若干行,供应用内日志查看器。日志按日滚动(文件名形如
	 *  `mc-launcher.log.<日期>`),取修改时间最新的那个;有界读取(末尾最多 512KiB)避免大日志卡 UI。
	 */
	readLogTail: (lines: number) => typedError<string, string>(__TAURI_INVOKE("read_log_tail", { lines })),
	/**  拉取轻量后端(mc-server)的新闻/公告。后端未运行/不可达时返回错误,UI 降级到空/错误态。 */
	fetchNews: () => typedError<NewsItem[], string>(__TAURI_INVOKE("fetch_news")),
	/**  Register a kobeMC account (email/password); establishes the session. */
	kobemcSignup: (email: string, password: string, name: string) => typedError<AuthUser, string>(__TAURI_INVOKE("kobemc_signup", { email, password, name })),
	/**  Log in to a kobeMC account; establishes the session cookie. */
	kobemcLogin: (email: string, password: string) => typedError<AuthUser, string>(__TAURI_INVOKE("kobemc_login", { email, password })),
	/**  The current kobeMC session user, or `None` if not logged in. */
	kobemcSession: () => typedError<{
	id: string,
	email?: string | null,
	name?: string | null,
	username?: string | null,
} | null, string>(__TAURI_INVOKE("kobemc_session")),
	/**  Log out of the kobeMC account (clears the server session). */
	kobemcLogout: () => typedError<null, string>(__TAURI_INVOKE("kobemc_logout")),
	/**
	 *  Remember a kobeMC account (upsert by email) in the OS keyring. When the keyring
	 *  is unavailable nothing is written (no plaintext on disk). `auto_login = true`
	 *  makes this the single auto-login account (clears the flag on the others).
	 */
	kobeSaveCredentials: (email: string, password: string, autoLogin: boolean) => typedError<null, string>(__TAURI_INVOKE("kobe_save_credentials", { email, password, autoLogin })),
	/**  The list of remembered kobeMC accounts (may be empty). */
	kobeListCredentials: () => typedError<KobeCredentials[], string>(__TAURI_INVOKE("kobe_list_credentials")),
	/**  Forget a remembered kobeMC account by email. */
	kobeRemoveCredentials: (email: string) => typedError<null, string>(__TAURI_INVOKE("kobe_remove_credentials", { email })),
	/**  Toggle whether a remembered account auto-logs-in at startup (at most one). */
	kobeSetAutoLogin: (email: string, autoLogin: boolean) => typedError<null, string>(__TAURI_INVOKE("kobe_set_auto_login", { email, autoLogin })),
	/**  Realms the logged-in user belongs to. */
	realmList: () => typedError<RealmSummary[], string>(__TAURI_INVOKE("realm_list")),
	/**  A single realm's summary. */
	realmGet: (realmId: string) => typedError<RealmSummary, string>(__TAURI_INVOKE("realm_get", { realmId })),
	/**
	 *  Share an instance as a realm: create it from the instance's current mods, then
	 *  stamp the realm binding onto that instance (host = owner). Returns the summary.
	 */
	realmCreate: (root: string, instanceId: string, name: string, mcVersion: string, loader: string, loaderVersion: string | null, expiresInSecs: number | null) => typedError<RealmSummary, string>(__TAURI_INVOKE("realm_create", { root, instanceId, name, mcVersion, loader, loaderVersion, expiresInSecs })),
	/**
	 *  Join a realm by code and create a **pending** local instance bound to it (no
	 *  core installed yet — that's "begin"). Returns the new instance id, or `None`
	 *  if the code is unknown/expired.
	 */
	realmJoin: (root: string, code: string) => typedError<string | null, string>(__TAURI_INVOKE("realm_join", { root, code })),
	/**
	 *  "Begin": for a freshly-joined (pending) instance, install the core (version +
	 *  loader from the manifest) then download the realm's mods. Idempotent on the
	 *  core. Progress streams over `realm://sync-progress`.
	 */
	realmBegin: (realmId: string, root: string, instanceId: string) => typedError<SyncReport, string>(__TAURI_INVOKE("realm_begin", { realmId, root, instanceId })),
	/**  Member list (with synced-version progress). */
	realmMembers: (realmId: string) => typedError<RealmMember[], string>(__TAURI_INVOKE("realm_members", { realmId })),
	/**
	 *  EasyTier lobby credentials for a realm (members only) — network name/secret +
	 *  external nodes (P2P public + optional our hosted relay). P1: fetch only.
	 */
	realmLobby: (realmId: string) => typedError<LobbyCreds, string>(__TAURI_INVOKE("realm_lobby", { realmId })),
	/**
	 *  联机大厅 P3 —— host 发布我可达的地址(`<虚拟IP>:<端口>`),成员据此一键加入。
	 *  边开世界边每 ~30s 调一次作心跳(server 端 90s 过期)。
	 */
	realmSetHost: (realmId: string, address: string) => typedError<null, string>(__TAURI_INVOKE("realm_set_host", { realmId, address })),
	/**
	 *  联机大厅 P3 —— 查领域当前(新鲜的)host:有人在主持则返回 `address` + `host_username`,
	 *  否则两者皆 `None`。成员轮询它来决定能否「加入游戏」。
	 */
	realmGetHost: (realmId: string) => typedError<RealmHost, string>(__TAURI_INVOKE("realm_get_host", { realmId })),
	/**  联机大厅 P3 —— 停止主持(清掉我的 host 记录)。非 host 调用是无害空操作。 */
	realmClearHost: (realmId: string) => typedError<null, string>(__TAURI_INVOKE("realm_clear_host", { realmId })),
	/**
	 *  联机大厅 P3 —— 探测本机 Minecraft 是否「对局域网开放」:加入 MC 局域网发现组播监听
	 *  ~3s,读到端口则返回。未开 / 探测失败 → `None`(绝不 panic / 阻塞超过 ~3s)。
	 */
	detectLanWorld: () => typedError<number | null, string>(__TAURI_INVOKE("detect_lan_world")),
	/**
	 *  开启某领域的 EasyTier 联机会话:取凭据 → 挑节点 → 构参 → **提权**拉起 easytier-core。
	 *  幂等:先停掉任何旧会话再起新的。UI 随后轮询 [`lobby_status`]。
	 */
	lobbyStart: (realmId: string, mode: string) => typedError<null, string>(__TAURI_INVOKE("lobby_start", { realmId, mode })),
	/**  断开当前 EasyTier 会话(容错:已停止也返回 Ok)。 */
	lobbyStop: () => typedError<null, string>(__TAURI_INVOKE("lobby_stop")),
	/**
	 *  查询联机会话状态:无会话 → `running:false`;有会话则跑 `easytier-cli peer` 解析。
	 *  cli 偶发失败不报错(返回 `running:true` + 空 peers),避免刚起步时 UI 抖动。
	 */
	lobbyStatus: () => typedError<LobbyStatus, string>(__TAURI_INVOKE("lobby_status")),
	/**
	 *  一次性提权:装一个 root 拥有 + setuid 的 `easytier-core` 副本,让之后的「开启联机」免授权。
	 *  返回安装后是否确已免密就绪。Windows 等暂不支持(返回 `false`)。
	 */
	lobbySetupPrivileged: () => typedError<boolean, string>(__TAURI_INVOKE("lobby_setup_privileged")),
	/**  是否已「免密就绪」:特权核心存在 + owner 为 root + 带 setuid 位。 */
	lobbyPrivilegedReady: () => typedError<boolean, string>(__TAURI_INVOKE("lobby_privileged_ready")),
	/**  Owner/admin republishes the manifest from an instance; returns new version. */
	realmPushManifest: (realmId: string, root: string, instanceId: string, mcVersion: string, loader: string, loaderVersion: string | null) => typedError<number, string>(__TAURI_INVOKE("realm_push_manifest", { realmId, root, instanceId, mcVersion, loader, loaderVersion })),
	/**  Dry-run: what syncing `instance_id` to the realm's manifest would change. */
	realmPlanSync: (realmId: string, root: string, instanceId: string) => typedError<SyncPlan, string>(__TAURI_INVOKE("realm_plan_sync", { realmId, root, instanceId })),
	/**
	 *  Reconcile `instance_id` to the realm manifest: download missing/changed mods,
	 *  optionally drop the ones the manifest no longer carries, then report progress
	 *  to the server. Progress streams over a dedicated `realm://sync-progress` event
	 *  (kept off `install://progress` so it can't collide with a concurrent install).
	 */
	realmSync: (realmId: string, root: string, instanceId: string, removeExtras: boolean) => typedError<SyncReport, string>(__TAURI_INVOKE("realm_sync", { realmId, root, instanceId, removeExtras })),
	/**  Owner/admin invites an accepted friend straight into the realm (no join code). */
	realmInvite: (realmId: string, userId: string) => typedError<null, string>(__TAURI_INVOKE("realm_invite", { realmId, userId })),
	/**  Owner sets a member's role (`admin`/`member`). */
	realmSetRole: (realmId: string, userId: string, role: string) => typedError<null, string>(__TAURI_INVOKE("realm_set_role", { realmId, userId, role })),
	/**  Owner removes another member (their own client clears its binding locally). */
	realmRemoveMember: (realmId: string, userId: string) => typedError<null, string>(__TAURI_INVOKE("realm_remove_member", { realmId, userId })),
	/**
	 *  Self-leave a realm and unbind it from the local instance (the instance stays;
	 *  if it was never synced it's just an empty shell that drops out of the list).
	 */
	realmLeave: (realmId: string, userId: string, root: string, instanceId: string) => typedError<null, string>(__TAURI_INVOKE("realm_leave", { realmId, userId, root, instanceId })),
	/**  Owner disbands the realm and unbinds it from the local instance. */
	realmDisband: (realmId: string, root: string, instanceId: string) => typedError<null, string>(__TAURI_INVOKE("realm_disband", { realmId, root, instanceId })),
	/**  Set the current user's username (required before friend search works). */
	friendSetUsername: (username: string) => typedError<null, string>(__TAURI_INVOKE("friend_set_username", { username })),
	/**  Search users by username prefix. */
	friendSearch: (q: string) => typedError<UserBrief[], string>(__TAURI_INVOKE("friend_search", { q })),
	/**  Send a friend request by user id. */
	friendRequest: (userId: string) => typedError<null, string>(__TAURI_INVOKE("friend_request", { userId })),
	/**  Accepted friends. */
	friendList: () => typedError<UserBrief[], string>(__TAURI_INVOKE("friend_list")),
	/**  Incoming pending friend requests. */
	friendRequests: () => typedError<UserBrief[], string>(__TAURI_INVOKE("friend_requests")),
	/**  Accept a pending request from `user_id`. */
	friendAccept: (userId: string) => typedError<null, string>(__TAURI_INVOKE("friend_accept", { userId })),
	/**  Decline a pending request from `user_id`. */
	friendDecline: (userId: string) => typedError<null, string>(__TAURI_INVOKE("friend_decline", { userId })),
	/**  Remove a friend. */
	friendRemove: (userId: string) => typedError<null, string>(__TAURI_INVOKE("friend_remove", { userId })),
	/**
	 *  Heartbeat the current user's presence; `activity` = the running instance name
	 *  (what they're playing), or `None` when idle.
	 */
	presenceHeartbeat: (activity: string | null) => typedError<null, string>(__TAURI_INVOKE("presence_heartbeat", { activity })),
	/**  The current user's last 50 notifications (newest first). */
	notifications: () => typedError<Notification[], string>(__TAURI_INVOKE("notifications")),
	/**  Mark every notification as read (called when the bell dropdown opens). */
	notificationsRead: () => typedError<null, string>(__TAURI_INVOKE("notifications_read")),
	/**
	 *  Bind a Microsoft identity to the current kobeMC user. `account_id` is the
	 *  selected Microsoft account's Minecraft profile UUID; `username` is its
	 *  gamertag/MC username at link time (informational).
	 */
	accountLinkMicrosoft: (accountId: string, username: string | null) => typedError<null, string>(__TAURI_INVOKE("account_link_microsoft", { accountId, username })),
	/**  List the current kobeMC user's linked identities. */
	accountIdentities: () => typedError<Identity[], string>(__TAURI_INVOKE("account_identities")),
	/**  Unlink a provider (e.g. `microsoft`) from the current kobeMC user. */
	accountUnlink: (provider: string) => typedError<null, string>(__TAURI_INVOKE("account_unlink", { provider })),
	/**
	 *  检查某实例(由 Modrinth 整合包安装)是否有更新:返回比当前来源版本更新的版本列表。
	 *  非整合包来源 / 非 modrinth / 缺 project_id 时返回空(前端据此不显示更新提示)。
	 */
	checkModpackUpdates: (root: string, id: string) => typedError<VersionDetail[], string>(__TAURI_INVOKE("check_modpack_updates", { root, id })),
	/**
	 *  把一个由 Modrinth 整合包安装的实例**就地更新**到指定版本:覆盖导入新包到既有实例,
	 *  再清理新版移除的受管理文件(移入回收站)。存档 / 实例配置 / 用户自行添加的 mod 均保留。
	 */
	applyModpackUpdate: (root: string, id: string, versionId: string) => typedError<ModpackUpdateDto, string>(__TAURI_INVOKE("apply_modpack_update", { root, id, versionId })),
	/**
	 *  一次性检查 `root` 下所有实例的可用更新(每实例:mod 更新数 + 整合包是否有新版)。
	 *  网络密集,前端仅按需调用;内部有界并发推进,单实例失败被跳过不影响整批。
	 *  只返回**至少有一项更新**的实例,前端据此点亮卡片角标。
	 */
	checkAllUpdates: (root: string) => typedError<InstanceUpdateInfo[], string>(__TAURI_INVOKE("check_all_updates", { root })),
	/**
	 *  Run one turn of the streaming chat agent for `session_id`, streaming every event
	 *  (text / reasoning / tool-call / tool-result / done / error) to the UI over the
	 *  typed `on_event` channel. The session transcript is kept server-side in
	 *  [`ChatSessions`] and threaded across turns; a second turn for the same session
	 *  while one is still streaming is rejected with a clear error.
	 * 
	 *  On failure the error is both returned as `Err(String)` **and** emitted as a
	 *  terminal [`AgentStreamEvent::Error`], so the UI always sees the stream end even
	 *  when the failure is pre-stream (e.g. a missing OpenRouter key). Treat
	 *  `Error`/`Done` as idempotent terminals: a mid-stream failure is emitted once by
	 *  the agent loop and again here as the guaranteed safety-net terminal.
	 */
	agentChat: (sessionId: string, message: string, onEvent: Channel<AgentStreamEvent>) => typedError<null, string>(__TAURI_INVOKE("agent_chat", { sessionId, message, onEvent })),
	/**
	 *  Reset a chat session: drop its stored transcript (in memory AND on disk) so
	 *  the next [`agent_chat`] starts a brand-new conversation.
	 */
	agentChatReset: (sessionId: string) => typedError<null, string>(__TAURI_INVOKE("agent_chat_reset", { sessionId })),
	/**  是否处于画廊模式(环境变量 `MC_GALLERY` 非空且非 "0")。前端据此决定是否自动跑截图流程。 */
	galleryEnabled: () => typedError<boolean, string>(__TAURI_INVOKE("gallery_enabled")),
	/**  抓「main」窗口当前画面到 `<data_dir>/gallery/<name>.png`,返回文件绝对路径。 */
	galleryCapture: (name: string) => typedError<string, string>(__TAURI_INVOKE("gallery_capture", { name })),
	/**  用已抓好的截图生成 `<data_dir>/gallery/index.html` 网格画廊,返回其绝对路径。 */
	galleryBuild: (shots: GalleryShot[]) => typedError<string, string>(__TAURI_INVOKE("gallery_build", { shots })),
};

/* Types */
/**  The three kinds of account the launcher supports. */
export type AccountKind = "offline" | "microsoft" | "yggdrasil";

/**  A persisted account as shown in the account switcher. */
export type AccountSummary = {
	kind: AccountKind,
	username: string,
	uuid: string,
	/**  True for the currently selected account. */
	selected?: boolean,
	/**  Whether the account owns Minecraft (Microsoft accounts only). */
	owns_game?: boolean,
};

/**
 *  A single streamed event from the lean tool-use chat agent
 *  (`mc_core::agent::chat`). This is the wire-level seam between the agent loop
 *  and any front-end: the loop pushes these through a `ChatEventSink`, and the
 *  Tauri command layer forwards them over an `ipc::Channel` — mirroring how
 *  long-running tasks stream [`Progress`].
 * 
 *  Serialized as an internally-tagged union (`{"type": "text_delta", ...}`) so
 *  the UI can `switch` on `type`.
 */
export type AgentStreamEvent = 
/**  A chunk of assistant-visible markdown text. */
{ type: "text_delta"; delta: string } | 
/**
 *  A chunk of model reasoning/thinking, when the provider exposes it
 *  (OpenRouter reasoning deltas). Purely informational; never the answer.
 */
{ type: "reasoning"; delta: string } | 
/**  The model invoked a deterministic tool with these JSON arguments. */
{ type: "tool_call"; name: string; 
/**
 *  The runtime field stays `serde_json::Value` (arbitrary JSON); the
 *  specta override shapes the generated TypeScript as [`JsonValue`].
 *  specta represents `serde_json::Value` as an *inline* recursive type,
 *  which specta-typescript cannot emit — so exporting the event as-is
 *  fails. The override changes only the emitted TS, never the wire bytes.
 */
args: JsonValue } | 
/**  A tool finished; `summary` is a short human-readable result line. */
{ type: "tool_result"; name: string; summary: string } | 
/**  The turn finished normally (no more events will follow). */
{ type: "done" } | 
/**  The turn failed; `message` describes why. */
{ type: "error"; message: string };

/**
 *  The authenticated user (better-auth user shape). The session lives in the
 *  reqwest cookie jar (better-auth sets a session cookie), so keep one
 *  `ServerClient` and its session persists across calls.
 */
export type AuthUser = {
	id: string,
	email?: string | null,
	name?: string | null,
	username?: string | null,
};

/**  一个 blocked 文件(CurseForge 作者禁第三方分发)的 UI 视图:需用户手动下载。 */
export type BlockedFileDto = {
	name: string,
	website_url: string,
	target_dir: string,
	required: boolean,
};

/**  profile 里的一条披风。`url` 是 PNG 预览;`alias` 是披风名(如 `Migrator`)。 */
export type CapeInfo = {
	id: string,
	url: string,
	alias?: string,
	/**  `ACTIVE` / `INACTIVE`。 */
	state?: string,
};

/**
 *  一个内容分类(`GET /tag/category` 的一项)。`header` 把分类分组
 *  (`categories` / `features` / `resolutions` / `performance impact`);
 *  `project_type` 指出该分类适用于哪个资源类型(`mod` / `modpack` / `shader` / …)。
 */
export type CategoryTag = {
	name: string,
	header: string,
	project_type: string,
};

/**
 *  The device-code prompt shown to the user. `device_code` is the opaque handle
 *  passed back to [`msa_login_poll`]; everything else is for display.
 */
export type DeviceCodeDto = {
	user_code: string,
	verification_uri: string,
	device_code: string,
	interval: number,
	expires_in: number,
};

/**
 *  Modrinth 的 facet 分类法:内容分类 / loader / 游戏版本。前端据此渲染过滤面板。
 *  注意:这些是平台动态数据(分类名直接来自 Modrinth),**不**走 i18n,原样展示。
 */
export type FacetTagsDto = {
	categories: CategoryTag[],
	loaders: LoaderTag[],
	game_versions: GameVersionTag[],
};

/**  项目画廊里的一张图。 */
export type GalleryImage = {
	url: string,
	title: string | null,
	description: string | null,
	featured: boolean,
};

/**  一张截图的元信息:`name` 对应 `<name>.png`,`title` 是画廊里显示的标题。 */
export type GalleryShot = {
	name: string,
	title: string,
};

export type GameExit = {
	id: string,
	/**  进程退出码(被信号杀死时可能为 `None`)。 */
	code: number | null,
	success: boolean,
	/**  非零退出时的人话崩溃原因(诊断命中才有)。 */
	reason: string | null,
	/**  崩溃诊断给出的可执行建议(可能为空)。 */
	suggestions: string[],
	/**  崩溃类别 slug(前端据此本地化类别标签,如 `out_of_memory`);诊断命中才有。 */
	category: string | null,
	/**  命中的关键日志行(截断到 200 字符),作为崩溃证据展示。 */
	matched: string | null,
	/**  异常退出时保留的日志尾部(最近若干行,换行连接),供折叠查看与「复制诊断」;正常退出为空。 */
	log_tail: string,
};

export type GameLog = {
	line: string,
	level: string,
};

/**  A `.minecraft`-style game directory that holds versions / libraries / assets. */
export type GameRoot = {
	name: string,
	path: string,
	kind: RootKind,
};

export type GameStarted = {
	id: string,
};

/**
 *  一个游戏版本(`GET /tag/game_version` 的一项)。`version_type` 区分
 *  `release` / `snapshot` / `alpha` / `beta`,前端默认可只展示 release。
 */
export type GameVersionTag = {
	version: string,
	version_type: string,
};

/**
 *  跨实例的全局启动器设置。
 * 
 *  所有字段都有合理默认值(见 [`Default`] 实现),所以即便 `settings.json`
 *  只写了部分字段,缺失的字段也会通过 serde 默认值补齐(配合 `#[serde(default)]`)。
 */
export type GlobalSettings = {
	/**  下载源:`"official"`(官方)或 `"bmclapi"`(镜像)。 */
	download_source?: string,
	/**  下载并发数。 */
	concurrency?: number,
	/**  新建实例的默认堆内存(MiB)。 */
	default_memory_mb?: number,
	/**  全局 Java 可执行文件路径。`None` 表示让启动器自动探测/安装。 */
	java_path?: string | null,
	/**
	 *  是否启用下载镜像。即使 `download_source` 是官方,该开关也能强制走镜像;
	 *  二者任一指向镜像即生效(见 [`GlobalSettings::mirror_resolver`])。
	 */
	use_mirror?: boolean,
	/**  界面语言标签(如 `"zh-CN"`、`"en-US"`)。 */
	language?: string,
	/**  可选的远端服务地址(例如皮肤站/账号服务/自建同步服务)。 */
	server_url?: string | null,
	/**  额外的自定义数据根目录列表(多游戏根/外部实例库)。 */
	custom_roots?: string[],
	/**
	 *  用户提供的 CurseForge API key(Prism 风格:用户自带 key 才能用 CurseForge)。
	 *  `None` 或空 = 回退到内建/环境 key(见 [`crate::modplatform::resolve_cf_api_key`]),
	 *  仍无则不注册 CurseForge provider。**secret**,勿打日志。
	 */
	cf_api_key?: string | null,
	/**
	 *  是否显示 kobeMC 社交相关 UI(账号 / 领域 / 好友)。`None` = 按部署场景取默认
	 *  (便携·和实例同级 → 关;桌面独立版 → 开,见 [`crate::paths::is_portable_deployment`]);
	 *  `Some(_)` = 用户在设置里的显式覆盖。
	 */
	social_enabled?: boolean | null,
};

/**
 *  One linked identity of the current kobeMC user (e.g. `credential` email, or
 *  `microsoft`). Mirrors `mc-server`'s `Identity`.
 */
export type Identity = {
	provider: string,
	account_id: string,
};

/**  `import_modpack` 的返回:建好的实例 id + 需手动处理的 blocked 文件 + 跳过的可选文件。 */
export type ImportOutcomeDto = {
	instance_id: string,
	blocked: BlockedFileDto[],
	skipped_optional: string[],
};

/**  一个已成功安装的 mod 记录。 */
export type InstalledMod = {
	/**  Modrinth project id。 */
	project_id: string,
	/**  落盘到 `mods/` 的文件名。 */
	file_name: string,
};

/**
 *  单个实例的启动设置。所有字段在 json 缺失时回退到 [`Default`],
 *  因此向 `instance.json` 增量添加字段不会破坏旧文件。
 */
export type InstanceConfig = InstanceConfig_Serialize | InstanceConfig_Deserialize;

/**
 *  单个实例的启动设置。所有字段在 json 缺失时回退到 [`Default`],
 *  因此向 `instance.json` 增量添加字段不会破坏旧文件。
 */
export type InstanceConfig_Deserialize = {
	/**  实例展示名;缺省时由上层用版本 id 兜底。 */
	name?: string | null,
	/**  分配给 JVM 的最大堆内存 (MB)。默认 2048。 */
	memory_mb?: number,
	/**  固定使用的 Java 可执行文件路径;缺省走全局 Java 选择逻辑。 */
	java_path?: string | null,
	/**  追加到自动生成 JVM 参数之后的额外参数。 */
	jvm_args?: string[],
	/**  追加到自动生成游戏参数之后的额外参数。 */
	game_args?: string[],
	/**  游戏窗口宽度 (像素);缺省用全局/游戏默认。 */
	width?: number | null,
	/**  游戏窗口高度 (像素);缺省用全局/游戏默认。 */
	height?: number | null,
	/**  是否以全屏启动。 */
	fullscreen?: boolean,
	/**  启动即自动加入的服务器地址 (`host` 或 `host:port`)。 */
	server?: string | null,
	/**
	 *  该实例从哪个平台的整合包安装而来(供「更新整合包」/UI 展示来源)。
	 *  仅在由 provider 发起、已知确切项目 id 的安装时写入;URL/裸 zip 导入留 `None`。
	 */
	source?: InstanceSource | null,
	/**
	 *  该实例所属的临时领域(host 为 owner)。加入领域时写入,退出/解散时清除。
	 *  「加入即建薄存根」模型下,realm 实例可能尚未装核心(见 list_instances 的 pending 分支)。
	 */
	realm?: RealmRef | null,
	/**
	 *  用户给该实例打的自由格式标签(可多个),用于库分组 / 按标签筛选。
	 *  空列表不写盘(`skip_serializing_if`),保持 `instance.json` 简洁。
	 */
	tags?: string[],
};

/**
 *  单个实例的启动设置。所有字段在 json 缺失时回退到 [`Default`],
 *  因此向 `instance.json` 增量添加字段不会破坏旧文件。
 */
export type InstanceConfig_Serialize = {
	/**  实例展示名;缺省时由上层用版本 id 兜底。 */
	name: string | null,
	/**  分配给 JVM 的最大堆内存 (MB)。默认 2048。 */
	memory_mb: number,
	/**  固定使用的 Java 可执行文件路径;缺省走全局 Java 选择逻辑。 */
	java_path: string | null,
	/**  追加到自动生成 JVM 参数之后的额外参数。 */
	jvm_args: string[],
	/**  追加到自动生成游戏参数之后的额外参数。 */
	game_args: string[],
	/**  游戏窗口宽度 (像素);缺省用全局/游戏默认。 */
	width: number | null,
	/**  游戏窗口高度 (像素);缺省用全局/游戏默认。 */
	height: number | null,
	/**  是否以全屏启动。 */
	fullscreen: boolean,
	/**  启动即自动加入的服务器地址 (`host` 或 `host:port`)。 */
	server: string | null,
	/**
	 *  该实例从哪个平台的整合包安装而来(供「更新整合包」/UI 展示来源)。
	 *  仅在由 provider 发起、已知确切项目 id 的安装时写入;URL/裸 zip 导入留 `None`。
	 */
	source?: InstanceSource | null,
	/**
	 *  该实例所属的临时领域(host 为 owner)。加入领域时写入,退出/解散时清除。
	 *  「加入即建薄存根」模型下,realm 实例可能尚未装核心(见 list_instances 的 pending 分支)。
	 */
	realm?: RealmRef | null,
	/**
	 *  用户给该实例打的自由格式标签(可多个),用于库分组 / 按标签筛选。
	 *  空列表不写盘(`skip_serializing_if`),保持 `instance.json` 简洁。
	 */
	tags?: string[],
};

/**  实例的整合包来源溯源:它从哪个平台的哪个项目/版本安装而来。 */
export type InstanceSource = {
	/**  平台标识(如 `"modrinth"`)。 */
	provider: string,
	/**  平台上的项目 id。 */
	project_id: string,
	/**  安装时所用的版本 id;未知时 `None`。 */
	version_id: string | null,
};

/**  A summary of an instance for list views. */
export type InstanceSummary = {
	id: string,
	name: string,
	/**  The base Minecraft version, e.g. "1.20.1". */
	mc_version: string,
	loader: LoaderKind,
	/**  Loader version if applicable. */
	loader_version?: string | null,
	/**  Relative icon path or builtin icon key. */
	icon?: string | null,
	/**  Epoch millis of last launch, 0 if never. */
	last_played?: number,
	/**  Whether the instance is currently running. */
	running?: boolean,
	/**
	 *  Whether the core (version + loader) is installed. A realm instance that's
	 *  been joined but not yet synced is `false` — it can't launch until "begin".
	 */
	installed?: boolean,
	/**  The realm this instance belongs to, if any (host = `owner`). */
	realm?: RealmRef | null,
	/**  Free-form user tags for grouping / filtering in the Library. */
	tags?: string[],
};

/**  批量更新检查里**单个实例**的结果:有多少个 mod 可更新、整合包本身是否有新版本。 */
export type InstanceUpdateInfo = {
	/**  实例 id。 */
	instance_id: string,
	/**
	 *  可更新的已启用 mod 数量(`check_mod_updates` 结果的长度)。
	 *  **仅对非整合包实例(散装 / 手动装 mod)统计**;整合包实例恒为 0——它的 mod
	 *  跟随整合包版本走,由「整合包更新」统一驱动,不在这里单独报。
	 */
	mod_updates: number,
	/**  该实例(由整合包安装)是否有比当前来源版本更新的整合包版本(仅 Modrinth 来源可判定)。 */
	modpack_update: boolean,
};

/**
 *  JavaInstall with the version flattened to a string (the core keeps it
 *  structured; the UI only displays it).
 */
export type JavaDto = {
	path: string,
	version: string,
	is_64bit: boolean,
	source: string,
};

/**
 *  A specta-exportable stand-in for arbitrary JSON (`serde_json::Value`), used
 *  only as the export type of [`AgentStreamEvent::ToolCall`]'s `args` field.
 * 
 *  specta registers `serde_json::Value` as an *inline* type, and since it is
 *  recursive (`Value` → `Vec<Value>` → `Value`) specta-typescript refuses to
 *  inline it — so any exported DTO carrying a bare `serde_json::Value` fails to
 *  generate. This named, self-referential enum exports cleanly as a recursive
 *  `JsonValue` union instead. It never participates in (de)serialization of an
 *  event — the real field stays `serde_json::Value` — so the wire format is
 *  unchanged; this type exists purely to shape the generated TypeScript.
 */
export type JsonValue = "Null" | boolean | number | null | string | JsonValue[] | { [key in string]: JsonValue };

/**  记住的一个 kobeMC 账号凭据。`auto_login` 为真的(至多一个)启动时自动登录。 */
export type KobeCredentials = {
	email: string,
	password: string,
	auto_login?: boolean,
};

/**  Mod loader families. */
export type LoaderKind = "vanilla" | "forge" | "neoforge" | "fabric" | "quilt" | "liteloader" | "optifine";

/**
 *  一个 loader(`GET /tag/loader` 的一项)。`supported_project_types` 指出该 loader
 *  适用于哪些资源类型(过滤面板据此只在相关 kind 下显示对应 loader)。
 */
export type LoaderTag = {
	name: string,
	supported_project_types: string[],
};

/**  某领域的联机大厅凭据(EasyTier 房间)。 */
export type LobbyCreds = {
	network_name: string,
	network_secret: string,
	nodes?: LobbyNode[],
};

/**
 *  一个 EasyTier external/relay 节点。`kind`:`"p2p"` = 公共共享节点(打洞后直连,我们零成本);
 *  `"hosted"` = 我们自建的中继(host 点,打洞失败时兜底)。
 */
export type LobbyNode = {
	kind: string,
	name: string,
	addr: string,
};

/**  `easytier-cli peer` 表里的一行(一个对端,或本机自己那行)。 */
export type LobbyPeer = {
	ipv4: string | null,
	hostname: string,
	cost: string,
	lat_ms: number | null,
	nat_type: string | null,
};

/**  联机大厅当前状态:是否在跑、本机虚拟 IP、对端列表(不含本机自己那行)。 */
export type LobbyStatus = {
	running: boolean,
	virtual_ip: string | null,
	peers: LobbyPeer[],
};

/**  One entry from Mojang's version manifest. */
export type ManifestVersion = {
	id: string,
	kind: ReleaseKind,
	url: string,
	/**  SHA1 of the version json (Mojang manifest_v2 provides this). */
	sha1?: string,
	/**  ISO-8601 release time. */
	release_time?: string,
};

/**  单个本地 mod 的元数据视图。字段尽量贴近 UI 列表展示所需。 */
export type ModInfo = {
	/**  磁盘上的实际文件名(含 `.disabled` 后缀,如有)。用作启停/删除的稳定标识。 */
	file_name: string,
	/**  是否启用 = 文件名不以 `.disabled` 结尾。 */
	enabled: boolean,
	/**  展示名;读不到元数据时回退为去掉扩展名的文件名。 */
	name: string,
	/**  版本号(部分 mod 用占位符如 `${version}`,原样保留)。 */
	version: string | null,
	/**  mod 内部 id(fabric `id` / quilt `id` / forge `modId`)。 */
	mod_id: string | null,
	/**  loader 家族:`fabric` / `quilt` / `forge` / `neoforge` / `unknown`。 */
	loader: string,
	/**  作者列表(各 loader 格式差异较大,这里统一拍平成字符串数组)。 */
	authors: string[],
	/**  描述(通常为一句话)。 */
	description: string | null,
	/**  文件字节大小。 */
	size: number,
};

/**
 *  「装最新版」mod 的结果:沿用核心的依赖解析报告,再带上需手动下载的 blocked 文件
 *  (CurseForge 作者禁第三方分发时)。`blocked` 非空时前端弹 BlockedFilesDialog 引导手动下。
 */
export type ModInstallReport = {
	installed: InstalledMod[],
	satisfied: string[],
	unresolved: string[],
	incompatible?: string[],
	blocked?: BlockedFileDto[],
};

/**
 *  一个可用的 mod 更新。携带应用更新所需的全部信息(下载地址 / 校验 / 目标文件名),
 *  这样 UI 拿到后无需再查一次即可直接调用 [`apply_mod_update`]。
 */
export type ModUpdate = {
	/**  当前磁盘上的文件名(启用态 `.jar`),应用更新后会被替换/删除。 */
	file_name: string,
	/**  展示名(取本地解析到的 mod 名,读不到时为文件名)。 */
	name: string,
	/**  当前版本号(本地元数据;可能缺失)。 */
	current_version: string | null,
	/**  最新版本号(Modrinth `version_number`)。 */
	new_version: string,
	/**  最新版本主文件的文件名(下载后的落盘名)。 */
	new_file_name: string,
	/**  下载地址。 */
	url: string,
	/**  最新文件 sha1(下载校验用;Modrinth 通常都提供)。 */
	sha1: string | null,
	/**  最新文件大小(字节)。 */
	size: number | null,
};

/**  整合包就地更新的返回:实例 id + 被清理的旧包文件 + 仍需手动下载 / 跳过的文件。 */
export type ModpackUpdateDto = {
	instance_id: string,
	/**  因新版本移除而被移入回收站的旧包文件相对路径。 */
	removed: string[],
	blocked: BlockedFileDto[],
	skipped_optional: string[],
};

export type NewsItem = {
	id: string,
	title: string,
	body: string,
	date: string,
	url?: string | null,
};

/**
 *  A notification addressed to the current user. `kind` is one of
 *  `friend_request` | `friend_accepted` | `realm_invite`; `actor_*` is who
 *  caused it and `realm_*` the realm it concerns (resolved server-side). `read`
 *  is whether the user has already seen it (cleared on bell open).
 */
export type Notification = {
	id: string,
	kind: string,
	actor_id?: string | null,
	actor_username?: string | null,
	realm_id?: string | null,
	realm_name?: string | null,
	created_at: string,
	read?: boolean,
};

/**  一个已安装包的列表视图。直接派生 `Serialize` 以便经 Tauri command 回传前端。 */
export type PackInfo = PackInfo_Serialize | PackInfo_Deserialize;

/**  一个已安装包的列表视图。直接派生 `Serialize` 以便经 Tauri command 回传前端。 */
export type PackInfo_Deserialize = {
	/**
	 *  磁盘上的文件(或目录)名,含可能的 `.disabled` 后缀——
	 *  这是后续 enable/disable/delete 操作的定位键。
	 */
	file_name: string,
	/**  是否启用(= 不以 `.disabled` 结尾)。 */
	enabled: boolean,
	/**  资源类型标签(`resourcepack` / `shader` / `datapack`),来自 [`PackKind::label`]。 */
	kind: string,
	/**  文件大小(字节);目录形态的数据包为 0(不递归求和,避免大目录扫描开销)。 */
	size: number,
	/**  资源包 `pack.mcmeta` 里的描述文本;读取失败 / 非资源包时为 `None`。 */
	description?: string | null,
};

/**  一个已安装包的列表视图。直接派生 `Serialize` 以便经 Tauri command 回传前端。 */
export type PackInfo_Serialize = {
	/**
	 *  磁盘上的文件(或目录)名,含可能的 `.disabled` 后缀——
	 *  这是后续 enable/disable/delete 操作的定位键。
	 */
	file_name: string,
	/**  是否启用(= 不以 `.disabled` 结尾)。 */
	enabled: boolean,
	/**  资源类型标签(`resourcepack` / `shader` / `datapack`),来自 [`PackKind::label`]。 */
	kind: string,
	/**  文件大小(字节);目录形态的数据包为 0(不递归求和,避免大目录扫描开销)。 */
	size: number,
	/**  资源包 `pack.mcmeta` 里的描述文本;读取失败 / 非资源包时为 `None`。 */
	description?: string | null,
};

/**
 *  本数据层管理的三类"包"资源。
 * 
 *  与 [`ResourceKind`] 的区别:`PackKind` 只覆盖"放在实例目录、按文件开关"的三类,
 *  不含 Mod / Modpack(它们的管理逻辑不同);并额外携带"落在哪个子目录"的信息。
 */
export type PackKind = "resource_pack" | "shader" | "datapack";

/**  当前账号的皮肤 / 披风快照。 */
export type ProfileSkins = {
	id: string,
	name: string,
	skins?: SkinInfo[],
	capes?: CapeInfo[],
};

/**  Progress report emitted by long-running tasks (download, verify, launch). */
export type Progress = {
	/**  Human-readable description of the current stage, e.g. "下载 libraries". */
	stage: string,
	/**  Units completed so far. */
	current: number,
	/**  Total units (0 if unknown). */
	total: number,
	/**  Instantaneous speed in bytes/sec (0 if not applicable). */
	speed_bps: number,
};

/**
 *  一个项目的展示详情(整合包详情页「简介」用):长描述正文(markdown)、
 *  画廊、外部链接等。比 [`SearchHit`] 多带 `body` / `gallery` / 链接,供详情页
 *  渲染一个像样的「简介」标签页(而不只是一句话 description)。
 */
export type ProjectDetail = {
	id: string,
	slug: string,
	title: string,
	/**  一句话简介。 */
	description: string,
	/**  完整介绍正文(markdown 原文,前端渲染它)。 */
	body: string,
	downloads: number,
	followers: number,
	icon_url: string | null,
	categories: string[],
	/**  画廊图片(已按 `ordering` 升序;`featured` 为推荐封面)。 */
	gallery: GalleryImage[],
	source_url: string | null,
	issues_url: string | null,
	wiki_url: string | null,
	discord_url: string | null,
};

export type ProjectSideSupport = "required" | "optional" | "unsupported" | "unknown";

/**
 *  One file the syncer reconciles into a member's instance. `path` is relative
 *  to the **instance dir**, e.g. `mods/sodium.jar`.
 */
export type RealmFile = {
	path: string,
	sha1?: string | null,
	sha512?: string | null,
	size?: number | null,
	/**  Download url (Modrinth/CurseForge). Absent ⇒ `manual` (member adds it). */
	url?: string | null,
	/**  `"modrinth"` | `"curseforge"` | `"manual"`. */
	source?: string | null,
};

/**
 *  Who is currently hosting a realm's LAN-opened world. Both fields are `None`
 *  when nobody is hosting (or the host's heartbeat went stale). `address` is
 *  `<virtual_ip>:<lan_port>` — pass it straight to Quick Play to join.
 */
export type RealmHost = {
	address?: string | null,
	host_username?: string | null,
};

/**  One realm member + how far they've synced. */
export type RealmMember = {
	user_id: string,
	username?: string | null,
	role: string,
	synced_version: number,
	joined_at?: string | null,
};

/**
 *  The realm an instance belongs to (临时领域), stored on the instance and
 *  surfaced for badges + the in-instance realm panel. An instance maps to at
 *  most one realm (1:1). For a freshly-joined instance the core isn't installed
 *  yet — [`InstanceSummary::installed`] is false until the user hits "begin".
 */
export type RealmRef = {
	realm_id: string,
	/**  Join code (for display / re-share). */
	code?: string | null,
	/**  This client's role in the realm: `owner` | `admin` | `member`. */
	role: string,
	/**  Realm display name (cached for offline display). */
	name?: string | null,
	/**  Target Minecraft version (so a pending instance can install on "begin"). */
	mc_version?: string | null,
	/**  Target loader (`fabric` etc.) for the pending install. */
	loader?: string | null,
	loader_version?: string | null,
};

/**  A realm as seen by a member (includes *their* role). */
export type RealmSummary = {
	id: string,
	code: string,
	name: string,
	owner_id: string,
	mc_version?: string | null,
	loader?: string | null,
	manifest_version: number,
	role: string,
	expires_at?: string | null,
};

/**  The release channel of a Minecraft version. */
export type ReleaseKind = "release" | "snapshot" | "old_beta" | "old_alpha";

/**  How a game-root directory was discovered. See `docs/07-directory-model-portability.md`. */
export type RootKind = 
/**  Detected next to / inside the launcher executable directory (portable). */
"portable" | 
/**  The OS's official `.minecraft` location. */
"official" | 
/**  A directory the user added manually. */
"custom" | 
/**  Auto-created fallback under the launcher data directory. */
"default";

/**  一条已保存的多人服务器记录(展示 + 快速进入用)。 */
export type SavedServer = {
	/**  显示名(可空 —— UI 用地址兜底)。 */
	name: string,
	/**  服务器地址(`host` 或 `host:port`)。 */
	address: string,
	/**  服务器图标:64×64 PNG 的 base64(不含 `data:` 前缀);无则 `None`。 */
	icon: string | null,
};

/**  单张截图的列表视图(不含图片字节)。 */
export type ScreenshotInfo = {
	/**  磁盘文件名(启停/删除/读取的稳定标识)。 */
	file_name: string,
	/**  文件字节大小。 */
	size: number,
	/**  修改时间(epoch 毫秒;取不到为 0)。用于倒序排列。 */
	modified: number,
};

/**
 *  Discover 多选 facet 过滤(可选)。空字段即"不按该维度过滤"。仅 Modrinth 消费这些
 *  (Modrinth 把 loader 放在 categories 维度、环境是 `client_side`/`server_side` facet);
 *  `provider==curseforge` 时这些被忽略,只用顶层 `game_version` / `loader`。
 */
export type SearchFacetsArg = {
	/**  多选内容分类(每个各成一个 AND 组)。 */
	categories?: string[],
	/**  多选 loader(合成一个 OR 组)。 */
	loaders?: string[],
	/**  多选游戏版本(合成一个 OR 组)。 */
	game_versions?: string[],
	/**  运行环境:`"client"` / `"server"`(其余忽略)。 */
	environment?: string | null,
	/**  仅开源项目(License facet)。 */
	open_source?: boolean | null,
};

/**  搜索结果中的一个项目(或 `get_project` 的精简视图)。 */
export type SearchHit = {
	id: string,
	slug: string,
	title: string,
	description: string,
	author: string,
	downloads: number,
	icon_url: string | null,
	/**
	 *  High-res landscape cover (Modrinth gallery / featured image). Preferred
	 *  over `icon_url` for card covers; the small square icon looks low-res when
	 *  upscaled to fill a 16:9 card.
	 */
	gallery_url?: string | null,
	categories: string[],
	client_side?: ProjectSideSupport,
	server_side?: ProjectSideSupport,
};

/**
 *  A server's reachability + status snapshot. Always returned (never an error):
 *  on any failure `online` is `false` and the optional fields are `None`.
 */
export type ServerStatus = {
	online: boolean,
	players_online: number | null,
	players_max: number | null,
	motd: string | null,
	version: string | null,
	latency_ms: number | null,
};

/**  profile 里的一条皮肤。`url` 是可直接 `<img>` 的 PNG;`variant` 为 `classic` / `slim`。 */
export type SkinInfo = {
	id: string,
	url: string,
	/**  模型变体:`classic`(经典)或 `slim`(纤细)。 */
	variant?: string,
	/**  `ACTIVE` / `INACTIVE`。 */
	state?: string,
};

/**  What a sync to a manifest *would* change, computed without touching disk. */
export type SyncPlan = {
	/**  Files in the manifest that are missing locally or fail their hash. */
	download: RealmFile[],
	/**
	 *  Paths (relative to the instance dir) under the managed dirs that are
	 *  present locally but absent from the manifest.
	 */
	remove: string[],
	/**  Manifest files with no download url — the member must add them by hand. */
	manual: RealmFile[],
	/**  Manifest version this plan targets. */
	version: number,
};

/**  Outcome of [`apply_sync`]. */
export type SyncReport = {
	downloaded: number,
	removed: number,
	/**  Filenames that failed to download (after retries). */
	failed: string[],
	/**  Files the member must still add by hand. */
	manual: RealmFile[],
	/**  The manifest version that was applied. */
	version: number,
};

/**  本机内存信息(供 UI 在内存滑块旁展示「系统内存 X GB」)。 */
export type SystemMemory = {
	/**  物理内存总量(MiB)。探测失败时为 0。 */
	total_mb: number,
};

/**  UI theme preference. */
export type ThemeConfig = {
	/**  "dark" or "light". */
	mode: string,
	/**  Accent hue 0-360. */
	hue: number | null,
	/**  Accent saturation 0-100. */
	saturation: number | null,
	/**  Accent lightness 0-100. */
	lightness: number | null,
};

/**
 *  A minimal public view of a user (search result / friend / pending request).
 * 
 *  Friend lists (`GET /v1/friends`) additionally carry presence: `online` (seen
 *  within the last 120s) and `activity` (what they're playing, only while
 *  online). Search / pending-request results leave these at their defaults
 *  (`false` / `None`).
 */
export type UserBrief = {
	id: string,
	username?: string | null,
	online?: boolean,
	activity?: string | null,
};

/**
 *  一个版本的展示用详情(整合包详情页:含 changelog / 发布时间 / 类型 / 下载数,
 *  以及该版本的 `.mrpack` 文件地址)。比统一的 [`ProjectVersion`] 多带 UI 信息。
 */
export type VersionDetail = {
	id: string,
	version_number: string,
	name: string,
	/**  `release` / `beta` / `alpha`。 */
	version_type: string,
	game_versions: string[],
	loaders: string[],
	/**  ISO 8601 发布时间。 */
	date_published: string,
	downloads: number,
	/**  该版本的更新日志(markdown 原文)。 */
	changelog: string,
	/**  该版本的 `.mrpack` 下载地址(供「安装此版本」用);无则 `None`。 */
	mrpack_url: string | null,
	mrpack_filename: string | null,
	file_size: number | null,
};

/**  显式选版安装的结果:落盘主文件 + (仅 mod)依赖解析摘要 + 需手动下载的 blocked 文件。 */
export type VersionInstallReport = {
	/**  主文件落盘名(被 blocked 时为空)。 */
	file: string,
	/**  新装入的 required 依赖数量(仅 mod;packs 恒为 0)。 */
	installed_deps: number,
	/**  找不到兼容版本、未能解决的 required 依赖 project_id(仅 mod)。 */
	unresolved: string[],
	/**  所装版本声明为不兼容的项目 project_id(冲突;仅 mod)。 */
	incompatible?: string[],
	/**  CurseForge 作者禁第三方分发时需用户手动下载的文件;非空时前端弹 BlockedFilesDialog。 */
	blocked?: BlockedFileDto[],
};

/**
 *  单个世界的概要信息(供 UI 列表展示)。
 * 
 *  字段全部是"已解算好的展示值",不暴露原始 NBT,UI 层无需了解 NBT 结构。
 */
export type WorldInfo = {
	/**  世界在 `saves/` 下的目录名(稳定标识,用于 backup/delete/rename 的入参)。 */
	folder: string,
	/**  世界显示名(`Data.LevelName`);读不到时回退为 `folder`。 */
	name: string,
	/**  游戏模式:`survival` / `creative` / `adventure` / `spectator` / `unknown`。 */
	game_mode: string,
	/**  上次游玩时间(epoch 毫秒);`0` 表示未知。 */
	last_played: number,
	/**  世界种子;读不到时为 `None`。 */
	seed: number | null,
	/**  世界目录递归大小(字节),用于展示占用空间。 */
	size_bytes: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

